server:
  port: 8081
  servlet:
    context-path: /hzy
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/testdb
      auto-index-creation: true
  resources:
    static-locations: file:D://upload
  mvc:
    static-path-pattern: /static/**
logging:
  level:
      dev: debug
      org:
        springframework:
          data:
            mongodb:
              core: DEBUG
baidu:
  appid: 20201103000607261
  securityKey: 26HE7Mq0AM_oITG01z_n
