server:
  port: 8081
  servlet:
    context-path: /hzy
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/testdb
      auto-index-creation: true
logging:
  level:
      dev: debug
      org:
        springframework:
          data:
            mongodb:
              core: DEBUG
